export type Language = 'es' | 'en';

export interface Ingredient {
  item: string; // English only - translations in separate table
  quantity: string;
}

export interface InstructionStep {
  description: string; // English only - translations in separate table
}

export interface Recipe {
  id: number; // Auto-generated by database
  title: string; // English only
  description: string; // English only
  author?: string;
  originalUrl: string;
  imageUrl?: string;
  prepTime: string;
  cookTime: string;
  servings: number;
  costEstimate?: string; // e.g. "$1.50 per serving"
  ingredients: Ingredient[];
  instructions: InstructionStep[]; // Array order is the step number
  nutrition?: {
    calories?: string;
    protein?: string;
    carbs?: string;
    fat?: string;
  };
  tags: string[];
  rating?: number; // Average rating (0-5)
  ratingCount?: number; // Number of ratings
  viewCount?: number; // Number of views
  createdAt: string; // ISO timestamp
  updatedAt: string; // ISO timestamp
}

// Translation types for fetching from database
export interface RecipeTranslation {
  recipeId: number;
  locale: string;
  title?: string;
  description?: string;
}

export interface IngredientTranslation {
  recipeId: number;
  ingredientIndex: number;
  locale: string;
  item?: string;
}

export interface InstructionTranslation {
  recipeId: number;
  stepIndex: number;
  locale: string;
  description?: string;
}

export enum LoadingState {
  IDLE = 'IDLE',
  LOADING = 'LOADING',
  SUCCESS = 'SUCCESS',
  ERROR = 'ERROR'
}

export interface SearchState {
  query: string;
  results: Recipe[];
  status: LoadingState;
  error?: string;
}
